import Error from "./error.js"
import metadata from "./metadata.js"
import replaces from "./replaces.js"

class interpreter {
  constructor (py) {
    this.python = py
    this.generated = `
      /*
        Generated by ${metadata.name} ${metadata.version}
        ${metadata.name} - library for run Python3 code in JavaScript.
        ${metadata.links.source_code}
      */
      let variables = {}
      let packages = []
      let variablesData = {}
    `
  }

  interpretation () {
    const code = py
    let interpreterData = {
      line: -1,
      symbol: -1
    }
    const lines = code.split("\n")
    const tab = "\t"
    for (interpreterData.line = 0; interpreterData.line < lines.length; interpreterData.line++) {
      const line = lines[interpreterData.line]
      const symbols = line.split("")
      for(interpreterData.symbol = 0; interpreterData.symbol < symbols.length; interpreterData.symbol++) {
        const getSymbol = (s) => {
          symbols[s]
        }
        const sNum = interpreterData.symbol
        const symbol = getSymbol(sNum)
      }
    }
  }
}

export default interpreter
