import { PyFS } from "./fs.js"
import Error from "./error.js"
import metadata from "./metadata.js"
import replaces from "./replaces.js"
import Import from "./import.js"

class interpreter {
  constructor (py, imports, runIn) {
    this.python = py
    this.generated = `
      /*
        Generated by ${metadata.name} ${metadata.version}
        ${metadata.name} - library for run Python3 code in JavaScript.
        ${metadata.links.source_code}
      */
      const types = {
        str: typeof "",
        int: typeof 0,
        float: typeof 1.5,
        complex: undefined,
        bool: typeof true,
        list: typeof [],
        function: typeof (() => {}),
        class: typeof (class { constructor () {} })
      };
      const jsTypes = {
        string: 'str',
        number: 'int',
        boolean: 'bool',
        array: 'object'
      };
      let variables = {
        str: function (text) {
          return toString(text);
        },
        int: function (num) {
          return +num;
        },
        bool: function (bool) {
          if (bool) {
            return true;
          } else {
            return false;
          };
        },
        type: function (text) {
          return jsTypes[typeof text];
        }
      };
      let packages = [];
      let variablesData = {
        "str": types.function,
        "int": types.function,
        "bool": types.function,
        "type": types.function
      };
    `
    this.imports = new Import(imports)
    this.isWeb = runIn === "browser"
    this.isVM = runIn === "safeMode"
    this.Fs = new PyFS(this.isWeb, this.isVM)
  }

  interpretation () {
    const code = py
    let interpreterData = {
      line: -1,
      symbol: -1,
      tabs: "",
      tabLevels: []
    }
    const lines = code.split("\n")
    const tab = "\t"
    const tab2 = "\t\t"
    for (interpreterData.line = 0; interpreterData.line < lines.length; interpreterData.line++) {
      const line = lines[interpreterData.line]
      const symbols = line.split("")
      if (line.startWith([interpreterData.tabs, tab2].join())) {
        const error = new Error("Invalid tabs", interpreterData)
        console.error(error.syntax())
        break
      }
      for(interpreterData.symbol = 0; interpreterData.symbol < symbols.length; interpreterData.symbol++) {
        const getSymbol = (s) => {
          symbols[s]
        }
        const sNum = interpreterData.symbol
        const symbol = getSymbol(sNum)
        if (sNum === 0) {
          if ([symbol, getSymbol(sNum + 1), getSymbol(sNum + 2), getSymbol(sNum + 3)].join("") === "from") {
            interpreterData.symbol = interpreterData.symbol + 3
          } else if ([symbol, getSymbol(sNum + 1), getSymbol(sNum + 2), getSymbol(sNum + 3), getSymbol(sNum + 4), getSymbol(sNum + 5)].join("") === "import") {
            interpreterData.symbol = interpreterData.symbol + 5
          } else if ([symbol, getSymbol(sNum + 1), getSymbol(sNum + 2)].join("") === "def") {
            this.generated += replaces.defStart
            interpreterData.tabs += tab2
            interpreterData.symbol = interpreterData.symbol + 2
          } else {
            const error = new Error(`Unknown command`, interpreterData)
            console.error(error.syntax())
            break
          }
        }
      }
    }
  }

  eval () {
    eval(this.generated)
  }

  func () {
    (new Function(this.generated))()
  }
}

export default interpreter
